### ISSUE TITLE
Requests: make a Level editor of Lucky Dime Caper, Castle of Illusion, Land of Illusion, Legend of Illusion, Daffy Duck in Hollywood, and Asterix (1991) all for Master System only. as well as a Coca Cola Kid level editor based on the reverse engineered code based on this editor.

### ISSUE THREAD

**Issue by ghost** [maxim-zhao/STH1EDWV#12]
the Level editor for these Master System games would be a Multi-Editor in a similar vein to https://github.com/spiiin/CadEditor
Lucky Dime Caper
Castle of Illusion
Land of Illusion
Legend of Illusion
Daffy Duck in Hollywood
Asterix (1991)

if DuckTales can get a Level editor, these should get the Level editor treatment too.

**Comment by F1660t03578314** [comment]
Update and Realized: changed my mind about the Lucky Dime Caper GG part, that one is acceptable to get the support in that WIP level editor too because these Game Gear difference having enough different to warrant adding GG support for Lucky Dime Caper too. (Land of Illusion, Legend of Illusion, and Daffy Duck in Hollywood on the other hand still don't need any sort of Game Gear support because not much differences aside from the smaller screen "Sonic 2" like screen crunch in GG compared to SMS, these latter 3 along with all the other SMS to GG ports that have from minor to no differences don't need the Level editor support at all, all you would get are the Screen crunch from these GG versions) (only Sonic 1 GG, Lucky Dime Caper GG, and Castle of Illusion GG are acceptible to add in their respective Master System level editors, Sonic 1 GG and Lucky Dime Caper GG has enough different to warrent GG support, while Castle of Illusion GG also runs in SMS mode).

here are the Game Gear differences for Lucky Dime Caper.
The layout of platforms, enemy positions are different.
In the Game Gear version, bonus items are pre-placed in the level, whereas in the Master System version they are only obtainable by killing enemies.
The Master System game allows you to back track, the Game Gear version does not.
Collecting five stars in the Master System game gives you limited invulnerability, the Game Gear version gives additional points.
When hit by an enemy, Donald loses his hammer weapon in the Master System version; it can be obtained as bonus item after killing an enemy. The hammer is not lost when hit by an enemy in the Game Gear version.

**Comment by maxim-zhao** [comment]
Not going to happen...
